"""add_rbac_fields

Revision ID: 156395ede22f
Revises: 13c426e84b5f
Create Date: 2025-12-18 07:21:28.460011
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '156395ede22f'
down_revision = '13c426e84b5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_equipment_factory_no', 'equipment', ['factory_no'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    op.drop_constraint('uq_equipment_factory_no', 'equipment', type_='unique')
    # ### end Alembic commands ###
