name: Test My Self-Hosted Runner

on:
  push:
    branches: [test-github-actions]
  workflow_dispatch:

jobs:
  test-runner:
    name: "Test My Runner"
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: "Greeting"
      run: echo "Hello Github Actions!"

    - name: Check access to the server
      run: ping -c 5 10.202.220.142

    - name: Check access to the non-existent server
      run: ping -c 5 10.202.220.140
